### ISSUE TITLE
Global Master - Recenzja kodu

### ISSUE THREAD

**Issue by GrzegorzDroid** [TrolQu/globalmaster-task#1]
Dzień dobry
Przeanalizowałem wykonane przez Pana zadanie. Wygląda w porządku, ale mam dwa zastrzeżenia:
- pod tekstem banera brakuje przyciemnienia, przez co jest nieco nieczytelny
- strona nie korzysta z czcionki, której używamy na naszej witrynie.

Pozdrawiam
Grzegorz Dziura | IT Specialist
Global Master

**Comment by TrolQu** [comment]
Witam, kod strony został poprawiony.
Mam nadzieję, że teraz spełni wymagania i Państwa odpowiedź będzie pozytywna.

Co do czcionek zaimportowałem je do strony oraz użyłem, ale nie jestem pewien czy to te same.
Jeśli będą jakieś zastrzeżenia co do strony to proszę o informacje i dokonam poprawek.

Pozdrawiam, 
Bartosz C.

**Comment by GrzegorzDroid** [comment]
Dzień dobry,
sprawdziłem wprowadzone zmiany, strona wygląda lepiej.
Skontaktujemy się z Panem przed terminem rozpoczęcia praktyk. W razie pytań proszę oczywiście pisać na nasz adres e-mailowy lub kontaktować się telefonicznie.

Pozdrawiam.
